### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by ramonjsantiago** [fredlo2010/Json2Model#19]

**Comment by fredlo2010** [comment]
Thanks for the help

I do not know TypeScript perhaps you can help me translate the bellow JSON 

````json
{
    "customer":{
        "firstName": "John",
        "lastName": "Doe"
    },
    "addresses": [
        {
            "street": "Faraway Creek",
            "number": 1234,
            "city": "Never-land"
        }
    ],
    "balance": 23234.23,
    "active": true
}
````

**Comment by ramonjsantiago** [comment]
Go to this site and paste the following code into the left panel, then click run inth right panel and press F12 to see the JavaScript console.

There are notationally more compact ways to do this in TypeScript. I tried to make it easier to translate.

class Address {
    public street : string;
    public number : string;
    public city   : string;

    constructor(street:string, number:string, city:string) {
        this.street = street;
        this.number = number;
        this.city   = city;
    }
}

class Customer {
    public firstName : string;
    public lastName  : string;

    constructor(firstName: string, lastName: string) {
        this.firstName = firstName;
        this.lastName  = lastName;
    }
}

class CustomerAccount {
    public customer : Customer;
    public addresses : Address [];
    public balance : number;
    public active : boolean;

    constructor(customer : Customer, addresses : Address [], balance : number, active : boolean) {
        this.customer = customer;
        this.addresses = addresses;
        this.balance = balance;
        this.active = active;
    }
}

let anAccount : CustomerAccount =
    new CustomerAccount(
        new Customer('John', 'Doe'),
        [
            new Address('Faraway Creek', '1234', 'Never-land') 
        ],
        23234.23,
        true
    );
	
console.log(JSON.stringify(anAccount, null, 4));

/*
   you should get
   
   {
    "customer": {
        "firstName": "John",
        "lastName": "Doe"
    },
    "addresses": [
        {
            "street": "Faraway Creek",
            "number": "1234",
            "city": "Never-land"
        }
    ],
    "balance": 23234.23,
    "active": true
    }
	
	printed out in the javascript console
*/

**Comment by ramonjsantiago** [comment]
Sorry about that last post, this one should be easier to read.

`class Address {
    public street : string;
    public number : string;
    public city   : string;

    constructor(street:string, number:string, city:string) {
        this.street = street;
        this.number = number;
        this.city   = city;
    }
}

class Customer {
    public firstName : string;
    public lastName  : string;

    constructor(firstName: string, lastName: string) {
        this.firstName = firstName;
        this.lastName  = lastName;
    }
}

class CustomerAccount {
    public customer : Customer;
    public addresses : Address [];
    public balance : number;
    public active : boolean;

    constructor(customer : Customer, addresses : Address [], balance : number, active : boolean) {
        this.customer = customer;
        this.addresses = addresses;
        this.balance = balance;
        this.active = active;
    }
}

let anAccount : CustomerAccount =
    new CustomerAccount(
        new Customer('John', 'Doe'),
        [
            new Address('Faraway Creek', '1234', 'Never-land') 
        ],
        23234.23,
        true
    );
	
console.log(JSON.stringify(anAccount, null, 4));

/*
   you should get
   
   {
    "customer": {
        "firstName": "John",
        "lastName": "Doe"
    },
    "addresses": [
        {
            "street": "Faraway Creek",
            "number": "1234",
            "city": "Never-land"
        }
    ],
    "balance": 23234.23,
    "active": true
    }
	
	printed out in the javascript console
*/	`

**Comment by fredlo2010** [comment]
Thanks a lot for the help.

The code yielded this output:

````typescript
class Input {
	public addresses: Array<Address>;
	public balance: number;
	public active: boolean;
	public customer: Customer;

	constructor(addresses: Array<Address>, balance: number, active: boolean, customer: Customer) {
		this.addresses = addresses;
		this.balance = balance;
		this.active = active;
		this.customer = customer;
	}
	load() {
		//TODO: Needs to be implemented.
	}
}

class Address {
	public number: number;
	public city: string;
	public street: string;

	constructor(number: number, city: string, street: string) {
		this.number = number;
		this.city = 
		city;
		this.street = street;
	}
}

class Customer {
	public firstName: string;
	public lastName: string;

	constructor(firstName: string, lastName: string) {
		this.firstName = firstName;
		this.lastName = lastName;
	}
}
````

**Comment by ramonjsantiago** [comment]
That works for me. Thank you.

**Comment by fredlo2010** [comment]
You are welcome :)
